### ISSUE TITLE
Stern does not support env variable settings defined in kube config

### ISSUE THREAD

**Issue by michaelgeorgeattard** [wercker/stern#122]
Given the following valid kube config section used to connect to an EKS cluster:

```
users:
- name: xxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - xxx
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: foo
```

Stern or its dependencies are not switching the `AWS_PROFILE` to `foo`, thus failing to connect to the EKS cluster.
