### ISSUE TITLE
Stern seems to not follow logs of new containers on restart

### ISSUE THREAD

**Issue by valer-cara** [wercker/stern#70]
### What

Stern does not print logs from restarted containers. If I re-run stern after a container failure/restart, the new container's logs are printed.

### Reproduce

Create the following failing pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo

spec:
  containers:
    - name: foo
      image: busybox
      command: ["sh", "-c", "touch /log; tail -f /log"]
      readinessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 5
        exec:
          command: ["sh", "-c", "echo $(date) ::: Readiness probe >> /log; grep imready /foo"]

      livenessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 5
        exec:
          command: ["sh", "-c", "echo $(date) ::: Liveness probe >> /log; grep imalive /foo"]
```

Check logs:
```
stern foo
```
