### ISSUE TITLE
stern does not support gcp auth provider

### ISSUE THREAD

**Issue by chrishiestand** [wercker/stern#9]
`kubectl config view`

```
...
users:
- name: gke_[context redacted]
  user:
    auth-provider:
      config:
        access-token: [redacted]
        expiry: 2016-11-03T19:19:58.276983808-07:00
      name: gcp
...
```

`stern --context=gke_[context redacted] searchstring`
```
failed to create clientset: No Auth Provider found for name "gcp"
```
